# Generated by Django 4.2.8 on 2023-12-09 01:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_order_delete_student"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="error_message",
            field=models.CharField(blank=True, max_length=320, null=True),
        ),
    ]
