dog_breed_list = {
    "Affenpinscher",
    "Afghan Hound",
    "Airedale",
    "American Bulldog",
    "Appenzeller",
    "Basenji",
    "Basset",
    "Beagle",
    "Bernese Mountain Dog",
    "Bichon Frise",
    "Black and Tan Coonhound",
    "Bloodhound",
    "Border Collie",
    "Boston Bull",
    "Bouvier Des Flandres",
    "Boxer",
    "Brabancon Griffon",
    "Briard",
    "Brittany Spaniel",
    "Bulldog",
    "Bull Mastiff",
    "Cairn",
    "Cardigan / Cardigan Welsh Corgi",
    "Chihuahua",
    "Chow",
    "Clumber",
    "Cocker Spaniel",
    "Collie",
    "Coonhound",
    "Corgi",
    "Dachshund",
    "Dalmatian",
    "Doberman",
    "English Foxhound",
    "English Setter",
    "English Springer",
    "EntleBucher",
    "Eskimo Dog",
    "Finnish Spitz",
    "French Bulldog",
    "German Shepherd",
    "German Short-haired Pointer",
    "Giant Schnauzer",
    "Golden Retriever",
    "Gordon Setter",
    "Great Dane",
    "Great Pyrenees",
    "Greater Swiss Mountain Dog",
    "Greyhound",
    "Groenendael",
    "Ibizan Hound",
    "Irish Setter",
    "Irish Terrier",
    "Irish Water Spaniel",
    "Irish Wolfhound",
    "Italian Greyhound",
    "Japanese Spaniel",
    "Keeshond",
    "Kelpie",
    "Kerry Blue Terrier",
    "King Charles Spaniel",
    "Komondor",
    "Kuvasz",
    "Labrador Retriever",
    "Lakeland Terrier",
    "Leonberg",
    "Lhasa",
    "Malamute",
    "Malinois",
    "Maltese Dog",
    "Mastiff",
    "Mexican Hairless",
    "Miniature Pinscher",
    "Miniature Poodle",
    "Miniature Schnauzer",
    "Newfoundland",
    "Norfolk Terrier",
    "Norwegian Elkhound",
    "Norwich Terrier",
    "Old English Sheepdog",
    "Otterhound",
    "Papillon",
    "Pekinese",
    "Pembroke / Pembroke Welsh Corgi",
    "Pitbull",
    "Pointer",
    "Pomeranian",
    "Poodle",
    "Pug",
    "Redbone",
    "Rhodesian Ridgeback",
    "Rottweiler",
    "Saint Bernard",
    "Saluki",
    "Samoyed",
    "Schipperke",
    "Scotch Terrier",
    "Scottish Deerhound",
    "Sealyham Terrier",
    "Shetland Sheepdog",
    "Shih-Tzu",
    "Siberian Husky",
    "Silky Terrier",
    "Soft-Coated Wheaten Terrier",
    "Staffordshire Bullterrier",
    "Standard Poodle",
    "Standard Schnauzer",
    "Sussex Spaniel",
    "Tibetan Mastiff",
    "Tibetan Terrier",
    "Toy Poodle",
    "Toy Terrier",
    "Vizsla",
    "Weimaraner",
    "Welsh Springer Spaniel",
    "West Highland White Terrier",
    "Whippet",
    "Wire-Haired Fox Terrier",
    "Yorkshire Terrier",
}