import React from 'react'
import withAuthenticatedLayout from '../components/hoc/withAuthenticatedLayout'

function BrowsePacks() {
  return (
    <section className="bg-white dark:bg-gray-900">
      <div className="flex flex-col gap-6 md:gap-12 w-full justify-between mx-auto max-w-screen-xl px-4 items-center mt-8 mb-16 md:my-16">
        <h2 className="text-4xl md:text-6xl font-extrabold tracking-tight text-center">
          {'Privacy Policy'.toUpperCase()}
        </h2>
        <h3>Introduction</h3>
        <p>
          At PhotoPacks.AI, your privacy is of utmost importance to us. This
          Privacy Policy outlines our practices regarding the collection, use,
          and disclosure of your information when you use our service and
          informs you about your privacy rights and how the law protects you.
        </p>

        <h3>Information We Collect</h3>
        <ol>
          <li>
            <strong>Personal Information:</strong>
            <ul>
              <li>
                Types of Data Collected: This may include, but is not limited
                to, names, email addresses, postal addresses, phone numbers, and
                other personal details.
              </li>
              <li>
                Collection Method: Directly provided by users through various
                means including registration, forms, and emails.
              </li>
            </ul>
          </li>
          <li>
            <strong>Usage Data:</strong>
            <p>
              Automatically collected data generated by the use of the website
              or from the website infrastructure (e.g., page visit duration).
            </p>
          </li>
          <li>
            <strong>Cookies and Tracking Data:</strong>
            <p>
              Cookies are used to track activity on our website and store
              certain information, aiding in enhancing your user experience.
            </p>
          </li>
        </ol>

        <h3>How We Use Your Information</h3>
        <ul>
          <li>For service provision and management.</li>
          <li>
            For communication including newsletters, marketing, or promotional
            materials.
          </li>
          <li>
            To improve our service based on your information and feedback.
          </li>
        </ul>

        <h3>Sharing Your Personal Information</h3>
        <p>
          We do not sell, trade, or rent users&apos; personal identification
          information to others. Generic aggregated demographic information not
          linked to any personal identification information may be shared with
          our business partners and advertisers.
        </p>

        <h3>GDPR Compliance</h3>
        <p>
          As per GDPR regulations, if you are a resident of the European
          Economic Area (EEA), you have certain data protection rights. These
          include the right to access, update, or request deletion of your
          personal information, the right to rectification, the right to object,
          the right to data portability, and the right to withdraw consent.
        </p>

        <h3>CCPA Compliance</h3>
        <p>
          As per the CCPA, if you are a resident of California, USA, you have
          certain rights regarding your personal information. This includes the
          right to access specific information and data portability rights, the
          right to request deletion of personal information, and the right not
          to be discriminated against for exercising these rights.
        </p>

        <h3>Security</h3>
        <p>
          We use commercially acceptable means to protect your personal
          information but cannot guarantee its absolute security.
        </p>

        <h3>Changes to This Privacy Policy</h3>
        <p>
          We reserve the right to update or change our Privacy Policy at any
          time and will notify you of any changes by posting the new policy on
          this page.
        </p>

        <h3>Contact Us</h3>
        <p>
          For any questions about this Privacy Policy, please contact us at:
          [Your Contact Information].
        </p>
      </div>
    </section>
  )
}

export default withAuthenticatedLayout(BrowsePacks, true)
