import React from 'react'
import withAuthenticatedLayout from '../components/hoc/withAuthenticatedLayout'

function Terms() {
  return (
    <section className="bg-white dark:bg-gray-900">
      <div className="flex flex-col gap-6 md:gap-12 w-full justify-between mx-auto max-w-screen-xl px-4 items-center mt-8 mb-16 md:my-16">
        <h2 className="text-4xl md:text-6xl font-extrabold tracking-tight text-center">
          {'Terms of Use'.toUpperCase()}
        </h2>
        <h1>Terms of Use for [Your Website Name]</h1>

        <h2>Introduction</h2>
        <p>
          Welcome to <strong>[Your Website Name]</strong>, a platform dedicated
          to the creation and purchase of artworks generated by Artificial
          Intelligence (AI). This website is operated by{' '}
          <strong>[Your Company Name]</strong> (&quot;we&quot;, &quot;us&quot;,
          &quot;our&quot;). By accessing or using our services, you agree to
          comply with these Terms of Service (&quot;Terms&quot;).
        </p>

        <h2>Acceptance of Terms</h2>
        <p>
          By registering on our site, placing an order, or using our services in
          any capacity, you agree to these Terms. If you are under 16 years old,
          you must use our Site under the supervision of a parent or guardian.
        </p>

        <h2>License and Usage</h2>
        <ul>
          <li>
            We grant you a non-exclusive, royalty-free, revocable, worldwide
            license to use our Site and services in accordance with these Terms.
          </li>
          <li>
            You may create, submit, or upload content, including creating
            AI-generated Artworks (&quot;User Content&quot;).
          </li>
          <li>
            Once your Artwork is delivered, Intellectual Property Rights in that
            specific Artwork are transferred to you for personal or commercial
            use, subject to the terms herein.
          </li>
        </ul>

        <h2>Prohibited Conduct</h2>
        <p>
          You must not engage in unlawful activities, defame, harass, threaten,
          or infringe upon the rights of others while using our Site. The use of
          our services to create or submit material that is abusive, deceptive,
          pornographic, or violates third-party rights is strictly prohibited.
        </p>

        <h2>Intellectual Property</h2>
        <p>
          All rights in materials developed, adapted, or created by us
          (excluding your specific Artwork) remain vested in us. We provide no
          warranties that you will be able to trademark or claim copyright
          ownership of our Artwork.
        </p>

        <h2>Orders and Payments</h2>
        <p>
          We reserve the right to accept or reject any order. All payments are
          to be made in advance using the methods specified on the Site. The
          sale of certain products or services may be subject to additional
          terms.
        </p>

        <h2>Termination and Modification</h2>
        <p>
          We reserve the right to terminate your access or modify these Terms
          and services at our discretion. Upon termination, you will lose access
          to your User Content and any related information.
        </p>

        <h2>Liability and Indemnification</h2>
        <p>
          Our liability is limited to the amount paid by you for the Artworks
          and services. You agree to indemnify us against any claims arising
          from your use of our services or violation of these Terms.
        </p>

        <h2>Dispute Resolution</h2>
        <p>
          These Terms are governed by the laws of{' '}
          <strong>[Your Jurisdiction]</strong>. Any disputes should first be
          attempted to be resolved through informal negotiations.
        </p>

        <h2>General Provisions</h2>
        <p>
          If any part of these Terms is found to be invalid or unenforceable,
          the remainder remains in effect. These Terms constitute the entire
          agreement between you and us regarding our service.
        </p>

        <h2>Contact Information</h2>
        <p>
          For any queries or concerns regarding these Terms, please contact us
          at <strong>[Your Contact Information]</strong>.
        </p>
      </div>
    </section>
  )
}

export default withAuthenticatedLayout(Terms, true)
