# Generated by Django 4.2.8 on 2023-12-11 23:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PromptPack",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=240)),
                ("prompts", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("subject_name", models.CharField(max_length=240)),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("man", "MAN"),
                            ("woman", "WOMAN"),
                            ("dog", "DOG"),
                            ("cat", "CAT"),
                        ],
                        default="man",
                        max_length=20,
                    ),
                ),
                (
                    "speed_type",
                    models.IntegerField(
                        choices=[
                            (100, "test (100)"),
                            (4160, "fast (4160)"),
                            (6240, "moderate (6240)"),
                            (8320, "slow (8320)"),
                        ],
                        default=4160,
                    ),
                ),
                (
                    "fulfillment_service",
                    models.CharField(
                        choices=[("runpod", "RUNPOD"), ("batch", "BATCH")],
                        default="runpod",
                        max_length=20,
                    ),
                ),
                ("is_processing", models.BooleanField(default=False)),
                ("is_success", models.BooleanField(null=True)),
                (
                    "error_message",
                    models.CharField(blank=True, max_length=320, null=True),
                ),
                ("training_image_urls", models.JSONField(blank=True, null=True)),
                ("inference_image_urls", models.JSONField(blank=True, null=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                (
                    "prompt_pack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="core.promptpack",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
