# Generated by Django 4.2.8 on 2023-12-12 22:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promptpack",
            name="name",
            field=models.CharField(max_length=240, unique=True),
        ),
    ]
