# Generated by Django 4.2.8 on 2023-12-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="fulfillment_service",
            field=models.CharField(
                choices=[("runpod", "RUNPOD"), ("batch", "BATCH")],
                default="runpod",
                max_length=20,
            ),
        ),
    ]
