# Generated by Django 4.2.8 on 2023-12-31 16:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="is_processing",
            new_name="is_submitted",
        ),
    ]
