# Generated by Django 4.2.8 on 2023-12-22 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_order_cropped_image_urls"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="prompts",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
