# Generated by Django 4.2.8 on 2023-12-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_order_fulfillment_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="inference_image_urls",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
