# Generated by Django 4.2.8 on 2023-12-13 02:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_promptpack_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="runpod_webhook_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
