# Generated by Django 4.2.8 on 2023-12-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_order_inference_image_urls"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="model_type",
            field=models.CharField(
                choices=[
                    ("man", "MAN"),
                    ("woman", "WOMAN"),
                    ("dog", "DOG"),
                    ("cat", "CAT"),
                ],
                default="man",
                max_length=20,
            ),
        ),
    ]
