# Generated by Django 4.2.8 on 2023-12-22 22:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_order_prompts"),
    ]

    operations = [
        migrations.RenameField(
            model_name="promptpack",
            old_name="name",
            new_name="internal_name",
        ),
        migrations.AddField(
            model_name="promptpack",
            name="pack_type",
            field=models.CharField(
                choices=[
                    ("man", "MAN"),
                    ("woman", "WOMAN"),
                    ("dog", "DOG"),
                    ("cat", "CAT"),
                ],
                default="man",
                max_length=20,
            ),
        ),
    ]
