# Generated by Django 4.2.8 on 2023-12-11 18:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_order_model_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="speed_type",
            field=models.CharField(
                choices=[
                    ("fast (4160)", "FAST"),
                    ("moderate (6240)", "MODERATE"),
                    ("slow (8320)", "SLOW"),
                ],
                default="fast (4160)",
                max_length=20,
            ),
        ),
    ]
