# Generated by Django 4.2.8 on 2023-12-22 22:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_rename_name_promptpack_internal_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="promptpack",
            name="display_name",
            field=models.CharField(default="", max_length=240),
        ),
    ]
