# Generated by Django 4.2.8 on 2023-12-22 22:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_promptpack_display_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="promptpack",
            name="preview_image",
            field=models.CharField(default="", max_length=240),
        ),
    ]
