# Generated by Django 4.2.8 on 2023-12-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_order_speed_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="speed_type",
            field=models.IntegerField(
                choices=[
                    (4160, "fast (4160)"),
                    (6240, "moderate (6240)"),
                    (8320, "slow (8320)"),
                ],
                default=4160,
            ),
        ),
    ]
