# Generated by Django 4.2.8 on 2024-01-02 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_order_is_uploaded"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhitelistedUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=100)),
            ],
        ),
    ]
