# Generated by Django 4.2.8 on 2023-12-14 23:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_order_zip_file_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="images_per_prompt",
            field=models.IntegerField(default=5),
        ),
    ]
