# Generated by Django 4.2.8 on 2023-12-26 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_promptpack_preview_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="prompt_pack",
            new_name="prompt_pack_1",
        ),
        migrations.AlterField(
            model_name="order",
            name="subject_name",
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name="promptpack",
            name="pack_type",
            field=models.CharField(
                choices=[
                    ("Man", "MAN"),
                    ("Woman", "WOMAN"),
                    ("Dog", "DOG"),
                    ("Cat", "CAT"),
                ],
                default="Man",
                max_length=20,
            ),
        ),
    ]
