# Generated by Django 4.2.8 on 2023-12-26 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_rename_prompt_pack_order_prompt_pack_1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="prompt_pack_1",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders_prompt_pack_1",
                to="core.promptpack",
            ),
        ),
    ]
