# Generated by Django 4.2.8 on 2024-01-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_whitelisteduser"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="pack_1_inference_image_urls",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="pack_2_inference_image_urls",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="pack_3_inference_image_urls",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="pack_4_inference_image_urls",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="pack_5_inference_image_urls",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
