# Generated by Django 4.2.8 on 2023-12-26 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_alter_order_prompt_pack_1"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="prompt_pack_2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders_prompt_pack_2",
                to="core.promptpack",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="prompt_pack_3",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders_prompt_pack_3",
                to="core.promptpack",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="prompt_pack_4",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders_prompt_pack_4",
                to="core.promptpack",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="prompt_pack_5",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders_prompt_pack_5",
                to="core.promptpack",
            ),
        ),
    ]
