# Generated by Django 4.2.8 on 2024-01-04 21:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_order_pack_1_inference_image_urls_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="inference_image_urls",
        ),
    ]
