# Generated by Django 4.2.8 on 2024-01-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_rename_zip_file_url_order_pack_1_zip_file_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="pack_2_zip_file_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="pack_3_zip_file_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="pack_4_zip_file_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="pack_5_zip_file_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
